// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8SBiv_ES-xbPwl6_BPsiOebE6UjM5tMI',
    appId: '1:828922304188:web:2a275668328490bcc1e2b9',
    messagingSenderId: '828922304188',
    projectId: 'flutter-chat-app-c6453',
    authDomain: 'flutter-chat-app-c6453.firebaseapp.com',
    storageBucket: 'flutter-chat-app-c6453.appspot.com',
    measurementId: 'G-46RGCRM5H8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCll6XTLO2CGhW7OCFiOH-Kz_KYlL5jOL0',
    appId: '1:828922304188:android:204243d5dfe33bcfc1e2b9',
    messagingSenderId: '828922304188',
    projectId: 'flutter-chat-app-c6453',
    storageBucket: 'flutter-chat-app-c6453.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5v0x-S9LKAqn22_kKoDFUR0N2LK-Itgk',
    appId: '1:828922304188:ios:b5b9978f44ababeac1e2b9',
    messagingSenderId: '828922304188',
    projectId: 'flutter-chat-app-c6453',
    storageBucket: 'flutter-chat-app-c6453.appspot.com',
    iosClientId: '828922304188-4sm2a1gca6gjir4aolsubmq71ecjtai8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5v0x-S9LKAqn22_kKoDFUR0N2LK-Itgk',
    appId: '1:828922304188:ios:b5b9978f44ababeac1e2b9',
    messagingSenderId: '828922304188',
    projectId: 'flutter-chat-app-c6453',
    storageBucket: 'flutter-chat-app-c6453.appspot.com',
    iosClientId: '828922304188-4sm2a1gca6gjir4aolsubmq71ecjtai8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp',
  );
}
